# Module manifest for module 'MonitorCalc'
# Generated by: Panos Grigoriadis
# Generated on: 02 Oct 2025

@{
RootModule        = 'MonitorCalc.psm1'
ModuleVersion     = '1.0.0'
GUID              = '0b244c1e-b471-49a0-914d-dc8dba4e4715'
Author            = 'Panos Grigoriadis'
#CompanyName       = ''
#Copyright         = ''
Description       = '...'
PowerShellVersion = '7.5'
#RequiredAssemblies = @()
#FormatsToProcess  = 'Formats\MonitorCalc.formats.ps1xml' # <-- uncomment this once done
#ScriptsToProcess  = ''
RequiredModules   = @(
                    )
FunctionsToExport = @(
                    'Get-ScreenSpec'
                    'Show-ScreenSpec'
                    )
AliasesToExport   = @(
                    'Map-LayoutValues'
                    )
FileList          = @(
                    'readme.md'
                    'MonitorCalc.psd1'
                    'MonitorCalc.psm1'
                    'Class\Classes.ps1'
                    'Data\OutputLayout.psd1'
                    'Data\FontStyles.psd1'
                    'Data\ResolutionNames.psd1'
                    'Data\ColorPalettes.psd1'
                    'Data\BorderLines.psd1'
                    'Data\DisplayInterfaces.psd1'
                    'Public\Get-ScreenSpec.ps1'
                    'Public\Show-ScreenSpec.ps1'
                    'Private\ConvertTo-Border.ps1'
                    'Private\ConvertTo-Cell.ps1'
                    'Private\ConvertTo-LayoutValues.ps1'
                    'Private\Get-Box.ps1'
                    'Private\Get-BoxLine.ps1'
                    'Private\Get-BoxMulti.ps1'
                    'Private\Measure-DisplayBandwidth.ps1'
                    )
PrivateData = @{
    PSData = @{
        Tags         = 'PowerShell', 'Monitor', 'Screen', 'Display'
        #ProjectUri   = ''
        ReleaseNotes = '...'
    }
}
}
